### PR TITLE
Fixes #9 Set up loklak with yaydoc

### LINKED ISSUE #9: Integrate Yaydoc to generate documentation
Integrate Yaydoc to generate documentation.
add the `yaydoc.yml` and specify all the necessary sub projects.

### PR DESCRIPTION
**Pull request by pri22296**
Fixes #9 

- Adds .yaydoc.yml with other loklak repos as subproject.
- Removed no longer needed files
- Added loklak logo

Preview: http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/1a7d9997-db22-49df-b5f1-73e9c85c418b_preview/

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y @mariobehling Please review

**Comment by imujjwal96** [comment]
Why haven't you used README.md as a startpage?

**Comment by pri22296** [comment]
Currently the links to subproject would not work from github. Would adding broken links to README be fine? Do you know of any alternative like specifying a backup link for such cases where in github we can just link to the github repo?

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please review

**Review by poonai — APPROVED** [review]

**Comment by imujjwal96** [comment]
No. I'm not aware of any.

**Review by imujjwal96 — APPROVED** [review]
Looks Good! Please also fix markdown in loklak_server. I haven't worked on it yet.

**Comment by pri22296** [comment]
@imujjwal96 Sure

**Pull request merged**
